Project_1/Tintin/Tintin/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from market_orders import views
from indicators import views
from crud import views
from detailed_symbol import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('market_orders', include('market_orders.urls')),
    path('', include('indicators.urls')),
    path('crud', include('crud.urls')),
    path('', include('detailed_symbol.urls')),

]

Project_1/Tintin/crud/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include


app_name = 'crud'

urlpatterns= [
    path('', views.RegistoListView.as_view(), name="crud"),
    path('', views.CRUD.as_view(), name="crud1"),
    path('create', views.RegistoCreateView.as_view(), name="create"),
    ]
"""path('crud/', views.CRUD.as_view(), name="crud"),"""

Project_1/Tintin/detailed_symbol/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'detailed_symbol'

urlpatterns= [
    path('detailed_symbol/', views.detailed_symbol, name="detailed_symbol")
]

Project_1/Tintin/indicators/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'indicators'

urlpatterns= [
    path('indicators/', views.indicators, name="indicators")
]

Project_1/Tintin/market_orders/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include


app_name = 'market_orders'

urlpatterns= [
    path('', views.market_orders, name="market_orders"),
    path('/testcall', views.testcall),
]

Project_1/Tintin/templates/default_layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title></title>
  </head>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'market_orders:market_orders' %}">Market Orders </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'indicators:indicators' %}">Indicators</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detailed_symbol:detailed_symbol' %}">Detailed Symbol</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'crud:crud' %}">Registo</a>
          </li>
        </ul>
      </div>
  </nav>
  <body>
    {% block body_block %}
    {% endblock %}
  </body>
</html>

Project_1/Tintin/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Start Page</title>
  </head>
  <body>
    <h1>This is the homepage of the project</h1>

  </body>
</html>